version: 1.0.{build}
image: Visual Studio 2015
init:
- cmd: cpan -T App::cpanminus
environment:
  HARNESS_PERL_SWITCHES: -MDevel::Cover=-db,cover_db,-coverage,statement,time,branch,condition,subroutine,pod-also_private-BUILD
install:
- cmd: >-
    cpanm -q --notest Dist::Zilla Devel::Cover::Report::Codecov Pod::Weaver::Section::Contributors Pod::Elemental::Transformer::List Dist::Zilla Dist::Zilla::App::Command::cover Dist::Zilla::App::Command::kwalitee Perl::Tidy

    dzil authordeps --missing | cpanm -q --notest

    dzil listdeps --author --missing | grep -v -E "^\[checked|tidied\]" | cpanm -q --notest
cache: C:\Perl
build: off
test_script:
- cmd: >-
    dzil kwalitee

    cd Text-Parser-*

    perl Makefile.PL

    dmake test

    cover
