---
abstract: 'Bare text parser, bundles other common "mundane" tasks.'
author:
  - 'Balaji Ramasubramanian <balajiram@cpan.org>'
build_requires:
  Test::Exception: '0'
  Test::More: '0'
  Test::Output: '0'
  constant: '0'
  parent: '0'
  perl: '5.012'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.012'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Parser
provides:
  Text::Parser:
    file: lib/Text/Parser.pm
    version: '0.753'
requires:
  Exception::Class: '0'
  Exporter: '0'
  Scalar::Util: '0'
  Try::Tiny: '0'
  perl: '5.012'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Parser
  homepage: https://github.com/balajirama/Text-Parser
  repository: https://github.com/balajirama/Text-Parser.git
version: '0.753'
x_contributors:
  - 'H.Merijn Brand - Tux <h.m.brand@xs4all.nl>'
x_generated_by_perl: v5.28.1
x_serialization_backend: 'YAML::Tiny version 1.73'
